config/routes.rb
Rails.application.routes.draw do
  get 'users/add_friends'
  get 'users/pending_requests'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"

  resources :friendships, only: [:create, :update, :destroy]
  resources :posts, only: [:index, :new, :create, :show]
  resources :users, only: [:show]

  resources :posts do
    post 'like', on: :member
    post 'dislike', on: :member
    post 'comment', on: :member
    post 'delete_comment', on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[github]
         
  validates :name, length: {minimum: 1}

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts
  has_many :comments
  has_many :likes

  def gravatar_url(size: 150)
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=identicon"
  end

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :github

  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   UserMailer.with(user: resource).welcome_email.deliver_later
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def add_friends
    @related_friendship_objects = Friendship.related_friendships(current_user.id).active_friendships

    @friends = @related_friendship_objects.map{ |obj| obj.user_id == current_user.id ? obj.friend_id : obj.user_id }

    @non_friends = User.where.not(id: @friends).where.not(id: current_user.id)
  end

  def pending_requests
    @pending_friendship_objects = Friendship.incoming_friendships(current_user.id).pending_friendships
  end

  def show
    @user = User.find(id=current_user.id)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/add_friends.html.erb
<div class="self-center border rounded-lg border-black w-1/3 shadow-lg bg-white p-4 flex flex-col">
  <h1 class="font-sans text-4xl font-bold mb-8 self-center">Add friends</h1>
    <% @non_friends.each do |person| %>
      <div class="border border-black flex justify-between items-center mb-4 text-lg bg-gray-100 shadow-sm rounded-md p-2">
        <div>
          <b><%= person.name %></b> <em>(<%= person.email %>)</em>
        </div>

        <form action="<%= friendships_url %>" method="post" class="w-fit">
          <input type="hidden" value="<%= current_user.id %>" name="sender_id">
          <input type="hidden" value="<%= person.id %>" name="receiver_id">
          <input type="Submit" value="Send Invite" class="bg-green-600 p-1 text-white rounded-lg hover:bg-white hover:text-black border-2 border-green-600 transition-all duration-200">
        </form>
      </div>
    <% end %>
</div>

app/views/users/pending_requests.html.erb
<div class="self-center border rounded-lg border-black w-2/5 shadow-lg bg-white p-4 flex flex-col">
  <h1 class="font-sans text-4xl font-bold mb-8 self-center">Notifications</h1>
    <% @pending_friendship_objects.each do |object| %>
      <div class="border border-black flex justify-between items-center mb-4 text-lg bg-gray-100 shadow-sm rounded-md p-2">
        
        <div>
          Friend request from 
          <b><%= User.find(id=object.user_id).name %></b> 
          <em>(<%= User.find(id=object.user_id).email %>)</em>
        </div>

        <div class="flex gap-5">
          <form method="patch" action="<%= friendship_url(object) %>">
            <input type="Submit" value="Accept" class="bg-green-600 py-1 px-2 text-white rounded-lg hover:bg-green-200 hover:text-black border-2 transition-all duration-200">
          </form>
          <form method="delete" action="<%= friendship_url(object) %>">
            <input type="Submit" value="Decline" class="bg-red-600 py-1 px-2 text-white rounded-lg hover:bg-red-200 hover:text-black border-2 transition-all duration-200">
          </form>
        </div>
      </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="self-center flex flex-col m-auto mt-[3%] space-y-8 border rounded-lg border-black w-1/3 shadow-lg items-center bg-white py-20 px-10">
  <h1 class="font-sans text-4xl font-bold mb-8">Users' Profile</h1>

  <%= image_tag(@user.gravatar_url, size: '150x150', alt: 'User Avatar') %>


  <% if @user.name.present? %>
    Name: <%= @user.name %> <br />
  <% end %>

  Email: <%= @user.email %> <br />

  <% if @user.bio %>
    Bio: <%= @user.bio %> <br />
  <% end %>
</div>