config/routes.rb
Rails.application.routes.draw do
  get 'users/add_friends'
  get 'users/pending_requests'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"

  resources :friendships, only: [:create, :update, :destroy]
  resources :posts, only: [:index, :new, :create, :show]
  resources :users, only: [:show]

  resources :posts do
    post 'like', on: :member
    post 'dislike', on: :member
    post 'comment', on: :member
    post 'delete_comment', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :status, inclusion: { in: ['pending', 'cancelled', 'accepted'] }

  # Returns Friendship objects which are related to current user
  def self.related_friendships(current_user_id)
    where(user_id: current_user_id).or(Friendship.where(friend_id: current_user_id))
  end

  # Returns Friendship objects which are not cancelled (accepted or pending)
  def self.active_friendships
    where(status: ['accepted', 'pending'])
  end

  def self.pending_friendships
    where(status: 'pending')
  end

  def self.incoming_friendships(current_user_id)
    where(friend_id: current_user_id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
  has_many :photos, as: :imageable

  validates :contents, presence: true

  def liked_by_user?(user)
    likes.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[github]
         
  validates :name, length: {minimum: 1}

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts
  has_many :comments
  has_many :likes

  def gravatar_url(size: 150)
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=identicon"
  end

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :bio, :profile_photo])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = Friendship.new(user_id: params[:sender_id], friend_id: params[:receiver_id], status: 'pending')

    if @friendship.save
      flash[:notice] = "Friend request sent to #{User.find(id=params[:receiver_id]).email}"
      redirect_to users_add_friends_url
    else
      flash[:notice] = "Something went wrong. Try again later"
      redirect_to users_add_friends_url
    end
  end

  def update
    @friendship = Friendship.find(id=params[:id])

    @friendship.status = 'accepted'

    if @friendship.save
      flash[:notice] = "Friend request accepted from #{User.find(id=@friendship.user_id).email}"
      redirect_to users_pending_requests_url
    else
      flash[:notice] = "Something went wrong. Try again later"
      redirect_to users_pending_requests_url
    end
  end

  def destroy
    @friendship = Friendship.find(id=params[:id])
    flash[:notice] = "Declined request from #{User.find(id=@friendship.user_id).email}"
    @friendship.destroy

    redirect_to users_pending_requests_url
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all
    @new_post = Post.new
    @post = Post.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # @posts = Post.all
    @posts = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(user_id: current_user.id, contents: params[:post][:contents])

    # Check if photo URL is provided
    if params[:post][:image_url].present?
      @photo = Photo.new(image_url: params[:post][:image_url])
      @post.photos << @photo
    end

    if @post.save
      flash[:notice] = "Post published!"
      redirect_to root_path
    else
      flash.now[:notice] = "Fill out the form correctly"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(id=params[:id])
  end

  def like
    @post = Post.find(id=params[:id])
    @like = @post.likes.build(user_id: current_user.id)

    if @like.save
      redirect_to posts_url, notice: "Post liked successfully"
    else
      flash[:notice] = "Failed to like post. Try again later"
      redirect_to posts_url
    end
  end

  def dislike
    @post = Post.find(id=params[:id])
    @like = @post.likes.find_by(user_id: current_user.id)
    
    if @like
      @like.destroy
      redirect_to posts_url, notice: "Disliked successfully"
    else
      redirect_to posts_url, notice: "Can't dislike at the moment. Try again later"
    end
  end

  def comment
    @post = Post.find(id=params[:id])
    @comment = @post.comments.build(user_id: current_user.id, contents: params[:contents])

    if @comment.save
      redirect_to posts_url, notice: "Comment published!"
    else
      redirect_to posts_url, notice: "Commenting went wrong. Try again later"
    end
  end

  def delete_comment
    @post = Post.find(id=params[:id])
    @comment = @post.comments.find(id=params[:comment_id])

    if @comment
      @comment.destroy
      redirect_to post_url(@post), notice: "Comment deleted successfully"
    else
      redirect_to post_url(@post), notice: "Can't delete comment at the moment."
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:contents)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def add_friends
    @related_friendship_objects = Friendship.related_friendships(current_user.id).active_friendships

    @friends = @related_friendship_objects.map{ |obj| obj.user_id == current_user.id ? obj.friend_id : obj.user_id }

    @non_friends = User.where.not(id: @friends).where.not(id: current_user.id)
  end

  def pending_requests
    @pending_friendship_objects = Friendship.incoming_friendships(current_user.id).pending_friendships
  end

  def show
    @user = User.find(id=current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracklet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: 'all' %>
    <%= javascript_importmap_tags %>

    <%= turbo_include_tags %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="bg-gradient-to-r from-sky-200 to-violet-300 flex flex-col">
    <% if flash[:notice].present? %>
      <div class="absolute top-0 right-0">
        <p class="bg-green-100 w-fit p-3 border-2 border-green-500 text-green-600 text-lg rounded-lg"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert].present? %>
      <div class="absolute top-0 right-0">
        <p class="bg-red-100 w-fit p-3 border-2 border-rose-500 text-red-600 text-lg rounded-lg"><%= alert %></p>
      </div>
    <% end %>

    <% if user_signed_in? %>
      <div class="fixed top-0 left-0-left h-screen w-60 m-0 flex flex-col gap-6 bg-white text-white shadow-xl px-6 py-4 border-r-2 border-black">
        <!--- User Icon -->
        <span class="text-black w-full flex justify-center gap-4 mb-8 mt-2">
          <%= current_user.name %>
          
          <%= image_tag(current_user.gravatar_url, size: '150x150', alt: 'User Avatar', class: "w-[40px] inline rounded-full border border-black") %>

        </span>

        <!-- Navbar -->
        <form method="get" action="<%= root_url %>">
          <button type="submit" class="w-full">
            <span class="align-bottom w-full bg-sky-300 hover:bg-violet-500 transition-all duration-300 text-lg flex justify-center gap-2 text-black hover:text-white rounded-xl px-4 py-2">
              Home 
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
              </svg>
            </span>
          </button>
        </form>
        
        <form method="get" action="<%= user_path(current_user) %>">
          <button type="submit" class="w-full">
            <span class="align-bottom w-full bg-sky-300 hover:bg-violet-500 transition-all duration-300 text-lg flex justify-center gap-2 text-black hover:text-white rounded-xl px-4 py-2">
              Profile 
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" 
              class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
            </span>
          </button>
        </form>
        
        <form method="get" action="<%= users_pending_requests_path(current_user) %>">
          <button type="submit" class="w-full">
            <span class="align-bottom w-full bg-sky-300 hover:bg-violet-500 transition-all duration-300 text-lg flex justify-center gap-2 text-black hover:text-white rounded-xl px-4 py-2">
              Notifications 
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
              </svg>
            </span>
          </button>
        </form>

        <form method="get" action="<%= users_add_friends_path(current_user) %>">
          <button type="submit" class="w-full">
            <span class="align-bottom w-full bg-sky-300 hover:bg-violet-500 transition-all duration-300 text-lg flex justify-center gap-2 text-black hover:text-white rounded-xl px-4 py-2">
              Find Friends 
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z" />
              </svg>
            </span>
          </button>
        </form>

        <form method="get" action="<%= edit_user_registration_path(current_user) %>">
          <button type="submit" class="w-full">
            <span class="align-bottom w-full bg-sky-300 hover:bg-violet-500 transition-all duration-300 text-lg flex justify-center gap-2 text-black hover:text-white rounded-xl px-4 py-2">
              Settings
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
            </span>
          </button>
        </form>

        <form method="delete" action="<%= destroy_user_session_path %>">
          <button type="submit" class="w-full">
            <span class="align-bottom w-full bg-sky-300 hover:bg-violet-500 transition-all duration-300 text-lg flex justify-center gap-2 text-black hover:text-white rounded-xl px-4 py-2">
              Log Out
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
              </svg>
            </span>
          </button>
        </form>
      </div>
        <%= button_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="self-center border rounded-lg border-black w-2/5 shadow-lg bg-white p-4 flex flex-col mb-16">
  <%= form_with model: @post do |f| %>
    <%= f.text_field :contents, placeholder: "What's on your mind?", class: "w-full rounded-tr-full pl-4 mb-2" %>

    <br />

    <%= f.text_field :image_url, placeholder: "Optional image url", class: "w-full rounded-br-full pl-4 mb-4" %>

    <%= f.submit "Create post", class: "bg-green-600 text-white w-32 text-lg h-8 rounded-lg shadow-md hover:bg-green-800 transition-all duration-300" %>
  <% end %>

  <% @post.errors.full_messages.each do |message| %>
    <div>
      <%= message %>
    </div>
  <% end %>
</div>

<turbo-frame id="post-listing" src="/posts" class="flex flex-col"></turbo-frame>

app/views/shared/_comments.html.erb
<form action="<%= comment_post_path %>" method="post">
  <input type="text" name="contents">
  <input type="Submit" value="Comment">
</form>

<% @post.comments.each do |comment| %>
  <div>
    <%= User.find(id=comment.user_id).email %>: <%= comment.contents %>
    <% if comment.user_id == current_user.id %>
      <%= button_to 'Delete', delete_comment_post_url(@post), params: {comment_id: comment.id} %>
    <% end %>
  </div>
<% end %>

app/views/shared/_like_dislike_functionality.html.erb
<% if @post.liked_by_user?(current_user) %>
  <%= button_to 'Dislike', dislike_post_url(@post), method: :post %>
<% else %>
  <%= button_to 'Like', like_post_url(@post), method: :post %>
<% end %>

app/views/shared/_post_body.html.erb
Content: <%= post.contents %> <br \>
Author: <%= post.user.email %> <br \>
Likes: <%= post.likes.count %> <br \>